In [1]:
import numpy as np

Khởi tạo lời giải ban đầu

In [103]:
# Thiết lập bàn cờ: queen[i] là cột của quân cờ hàng i
N=8
queen = np.array(range(N))

[7 4 1 2 0 3 6 5]


In [ ]:
# Khởi tạo bằng hoắn vị: mỗi quân cờ sẽ khác hàng và cột
np.random.shuffle(queen)
print(queen)

In [133]:
# Khởi tạo ngẫu nhiên hoàn toàn: mỗi quân hậu đều có vị trí tùy ý
for i in range(N):
    queen[i]= np.random.random_integers(N-1)
print(queen)

[6 3 2 2 3 1 6 4]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 7 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


Các hàm sử dụng trong quá trình tối ưu

In [68]:
# biểu diễn kết quả trên bàn cờ NxN
def show(state):
    for i in range(N):
        row = np.zeros(N)
        row[state[i]]=1
        print(row)

In [125]:
#  hàm mục tiêu ứng với trạng thái state

def obj_func(state):
    obj =0
    for i in range(N):
        for j in range(i+1,N):
            if state[i]==state[j]:
                obj+=1
            elif state[i]-i==state[j]-j:
                obj+=1
            elif state[i]+i==state[j]+j:
                obj+=1

    return obj

In [73]:
# tìm kiếm hàng xóm của trạng thái state

def neighbor(state):
    neighbor =[]
    for i in range(N):
        cur_row_i =state[i]      
        for j in range(N):
            if j !=cur_row_i:
                temp=np.array(state)
                temp[i]=j
                neighbor.append(temp)
    return neighbor

In [134]:
# vòng lặp chính
while(True):
    cur_optimum = obj_func(queen)
    next_state = queen
    for neighborState in neighbor(queen):
        if cur_optimum > obj_func(neighborState):
             cur_optimum= obj_func(neighborState)
             next_state = neighborState
    if (next_state==queen).all():
        show(next_state)
        print("Cost:",cur_optimum)
        break
    else:
        queen=next_state

[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
Cost: 0
